version: '3.8'
services:
  # Define the network function to be scaled
  skeleton:
    image: "cont_nf_test:latest"
    volumes:
      - /tmp/rx/{{.Task.Slot}}:/tx_pipe
      - /tmp/tx/{{.Task.Slot}}:/rx_pipe
    working_dir: /container
    command: ./build/app/cont_nf
